sources:
  - name: networking-wiki
    repo: adi-param/networking-wiki
    branch: main
    localPath: ../networking-wiki
    learningTopic: networking
    paths:
      - docs/**/*.md

  - name: enterprise-security-governance
    repo: adi-param/enterprise-security-governance
    branch: main
    localPath: ../enterprise-security-governance
    paths:
      - docs/**/*.md

  - name: aws
    repo: adi-param/aws
    branch: main
    localPath: ../aws
    learningTopic: aws
    paths:
      - docs/**/*.md

  - name: threat-modeling-playbook
    repo: adi-param/threat-modeling-playbook
    branch: main
    localPath: ../threat-modeling-playbook
    paths:
      - docs/**/*.md
